project:
  type: website

website:
  title: "William Okech"
  site-url: "https://williamokech.com/"
  description: "This is William Okech's personal Blog."
  favicon: william_profile.jpg
  navbar:
    right:
      - text: Resume
        href: blog_cv/Resume_William_Okech_Website_2024.pdf
      - text: Blog
        href: blog.qmd
      - text: Projects
        menu:
          - text: Web Apps
            href: portfolio/web_apps.qmd
          - text: Data Visualization  
            href: portfolio/data_viz.qmd
      - text: Training Materials
        menu:
          - text: Books
            href: portfolio/books.qmd
          - text: Email Courses
            href: portfolio/email.qmd
          - text: Presentations
            href: portfolio/presentations.qmd
      - text: Readings
        menu:
          - text: STEM-specific
            href: readings/reading_stem.qmd
          - text: For Everyone
            href: readings/reading_general.qmd
      - icon: rss
        href: blog.xml
#  cookie-consent:
#    type: express
#    style: headline
#    palette: dark
  google-analytics:
    tracking-id: "G-1VX0Q2FQEV"
    anonymize-ip: true
  page-footer:
    left: "Website made using [Quarto](https://quarto.org/), by William Okech. License: [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)"

format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto

editor: visual

comments:
  giscus:
    repo: wokech/blog-main
    
extensions:
  - jmgirard/embedpdf