project:
  type: website

website:
  title: "William Okech"
  site-url: "https://williamokech.netlify.app/"
  description: "This is William Okech's personal Blog."
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - text: Resume
        file: blog_cv/blog_cv_jun_2022.pdf
      - text: Data Analysis Tools 
        menu: 
          - href: resources/r_rstudio_shiny.qmd
          - href: resources/python.qmd
          - href: resources/data_viz.qmd
          - href: resources/git_github.qmd
          - href: resources/quarto_links.qmd
      - text: Data Science Resources
        menu: 
          - href: resources/ml_and_ai.qmd
          - href: resources/sports_data_sci.qmd
          - href: resources/env_data_sci_gis.qmd
      - text: Miscellaneous
        menu:
          - href: resources/biox.qmd
          - href: resources/non_ac_reading.qmd
      - icon: github
        href: https://github.com/wokech
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/willyokech
        aria-label: Twitter
  google-analytics: "G-1VX0Q2FQEV"
  page-footer:
    left: "Blog made using [Quarto](https://quarto.org/), by William Okech. License: [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)"
    right:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/willyokech
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/williamokech/
    - icon: github
      text: Github
      href: https://github.com/wokech
    - icon: envelope
      text: Email
      href: mailto:willyokech@gmail.com
      
format:
  html:
    theme: spacelab
    css: styles.css

execute:
  freeze: auto

editor: visual

comments:
  giscus:
    repo: wokech/blog-main