project:
  type: website

website:
  title: "William Okech"
  site-url: "https://williamokech.com/"
  description: "This is William Okech's personal Blog."
  favicon: william_profile.jpg
  navbar:
    right:
      - text: Resume
        file: blog_cv/Resume_William_Okech_Website_2024.pdf
      - text: Blog
        file: blog.qmd
      - text: Projects
        file: portfolio/projects.qmd
      - text: Training Materials
        file: portfolio/training_materials.qmd
      - text: Readings
        file: readings/readings.qmd
      - icon: rss
        href: blog.xml
#  cookie-consent:
#    type: express
#    style: headline
#    palette: dark
  google-analytics:
    tracking-id: "G-1VX0Q2FQEV"
    anonymize-ip: true
  page-footer:
    left: "Website made using [Quarto](https://quarto.org/), by William Okech. License: [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)"

format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto

editor: visual

comments:
  giscus:
    repo: wokech/blog-main