project:
  type: website

website:
  title: "William Okech"
  site-url: "https://williamokech.netlify.app/"
  description: "This is William Okech's personal Blog."
  navbar:
    right:
      - text: Resume
        file: blog_cv/Resume_William_Okech_Website_2023.pdf
      - blog.qmd
      - text: Resources 
        menu: 
          - href: resources/biox/biox.qmd
          - href: resources/ds_ml_ai/ds_ml_ai_all.qmd
          - href: resources/programming/programming.qmd
          - href: resources/random_interests/rand_int.qmd
          - href: resources/readings/readings.qmd
          - href: resources/teaching/teach_res.qmd
      - icon: github
        href: https://github.com/wokech
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/willyokech
        aria-label: Twitter
      - icon: medium
        href: https://medium.com/@willyokech
        aria-label: Medium
      - icon: linkedin
        href: https://www.linkedin.com/in/williamokech/
        aria-label: LinkedIn
      - icon: rss
        href: blog.xml
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-1VX0Q2FQEV"
    anonymize-ip: true
  page-footer:
    left: "Blog made using [Quarto](https://quarto.org/), by William Okech. License: [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)"
    right:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/willyokech
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/williamokech/
    - icon: github
      text: Github
      href: https://github.com/wokech
    - icon: medium
      text: Medium
      href: https://medium.com/@willyokech
    - icon: envelope
      text: Email
      href: mailto:willyokech@gmail.com
    
      
format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto

editor: visual

comments:
  giscus:
    repo: wokech/blog-main