project:
  type: website

website:
  title: "William Okech"
  site-url: "https://williamokech.com/"
  description: "This is William Okech's Personal Blog."
  favicon: william_profile.jpg
  navbar:
    right:
      - text: Resume
        href: blog_cv/Resume_William_Okech_Website_jan_2026.pdf
      - text: Blog
        href: blog.qmd
      - text: Projects
        menu:
        - text: Data Visualization
          href: portfolio/data_viz.qmd
        - text: Web Apps
          href: portfolio/web_apps.qmd
      - text: Teaching Website
        href: https://wokech.github.io/
      - text: Readings
        href: readings/reading_general.qmd
#  cookie-consent:
#    type: express
#    style: headline
#    palette: dark
  google-analytics:
    tracking-id: "G-1VX0Q2FQEV"
    anonymize-ip: true
  page-footer:
    left: "Website made using [Quarto](https://quarto.org/), by William Okech. The views and opinions expressed on this website are solely those of the author and do not necessarily reflect the views of the author’s employer or any affiliated organizations. License: [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)"

format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto

editor: visual

comments:
  giscus:
    repo: wokech/blog-main
    
extensions:
  - jmgirard/embedpdf