---
title: "Bioinformatics and Computational Biology"
toc: true
---

## Bioinformatics Blogs

1)  [JT Leek](https://github.com/jtleek)
2)  [Karolis Koncevičius](http://karolis.koncevicius.lt/)
3)  [Eytan Ruppin](https://ccr.cancer.gov/staff-directory/eytan-ruppin)
4)  [Lior Pachter](https://pachterlab.github.io/)
5)  [Jean Fan](https://jef.works/)
6)  [Phenomics](https://phenomic.ai/#papers)
7)  [Liu Lab](https://liulab-dfci.github.io/)
8)  [Costa Lab](https://www.costalab.org/teaching/)
9)  [Ming Tang](https://divingintogeneticsandgenomics.rbind.io/)
10) [Karl Broman](https://kbroman.org/)
11) [Krishnaswamy Lab](https://www.krishnaswamylab.org/)
12) [Philip Compeau](https://compeau.cbd.cmu.edu/)
13) [ZHOU LAB](https://zhou-lab.github.io/index.html)
14) [James Zou](https://www.james-zou.com/research)

## Bioinformatics Basics

1)  [Learning Bioinformatics At Home](https://github.com/harvardinformatics/learning-bioinformatics-at-home)
2)  [Welcome to a Little Book of R for Bioinformatics](https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/)
3)  [Introduction to Genomics for Engineers](https://learngenomics.dev/)
4)  [Introduction to Computational Biology](https://biodatascience.github.io/compbio/)
5)  [Childhood Cancer Data Lab](https://www.ccdatalab.org/)
6)  [SDS 348, Computational Biology and Bioinformatics 2019](https://wilkelab.org/classes/SDS348_spring_2019.html)
7)  [SDS 348, Computational Biology and Bioinformatics 2020](https://wilkelab.org/classes/SDS348_spring_2020.html)
8)  [Modern Statistics for Modern Biology](https://www.huber.embl.de/msmb/)
9)  [CELL BIOLOGY BY THE NUMBERS](http://book.bionumbers.org/)
10) [BMI 702 \| Biomedical Artificial Intelligence](https://zitniklab.hms.harvard.edu/BMI702/)
11) [Bioinformatics Research Network](https://www.bioresnet.org/)
12) [Bioinformatics Starter Pack](https://khushbupatel.notion.site/Bioinformatics-Starter-Pack-ae982892a9fb44569f735abc52ec9dd8)
13) [DIY Transcriptomics](https://diytranscriptomics.com/)
14) [BIG Bioinformatics](https://www.bigbioinformatics.org/)
15) [Biodatascience101](https://biodatascience101.github.io/)
16) [RNA-Seq Blog](https://www.rna-seqblog.com/)
17) [Biological Architecture Reading Roadmap](https://github.com/francisglee/biological-architecture-primer)
18) [Introduction to biological circuit design](https://biocircuits.github.io/chapters/01_intro_to_circuit_design.html)
19) [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/)
20) [Single-cell best practices](https://www.sc-best-practices.org/preamble.html)
21) [BD2K-LINCS DATA COORDINATION AND INTEGRATION CENTER](https://lincs-dcic.org/)
22) [Exploring Spatial Omics](https://aquila.cheunglab.org/)
23) [CRISPRpedia](https://innovativegenomics.org/crisprpedia/)
24) [COLAUTTI LAB](https://ecoevogeno.org/)
25) [R2 Genomics Analysis and Visualization Platform](https://hgserver1.amc.nl/cgi-bin/r2/main.cgi?open_page=login)
26) [Intro to Biomedical Data Science](http://bioconnector.github.io/bims8382/index.html)
27) [Biomedical Data Science](http://genomicsclass.github.io/book/)
28) [The Top 15 Machine Learning Data Science Bioinformatics Open Source Projects](https://awesomeopensource.com/projects/bioinformatics/data-science/machine-learning)
29) [Data Science for the Biomedical Sciences](https://ds4biomed.tech/)
30) [What is genomics?](https://www.genomicseducation.hee.nhs.uk/education/core-concepts/what-is-genomics/)
31) [20 YouTube Channels Every Bioinformatician Should Follow](https://bioinformaticamente.com/2022/05/08/20-youtube-channels-every-bioinformatician-should-follow/)
32) [Genomic Data Science Community Network](https://www.gdscn.org/home)
33) [Engineering Biology Research Consortium](https://ebrc.org/curriculum-module-introduction-to-engineering-biology/)
34) [7 Books for you to learn bioinformatics](https://crazyhottommy.blogspot.com/2022/11/7-books-for-you-to-learn-bioinformatics.html)
35) [Data Analysis for the Life Sciences (Free E-book)](https://leanpub.com/dataanalysisforthelifesciences)
36) [Practical Computing for Biologists](https://practicalcomputing.org/)
37) [A Primer for Computational Biology](https://open.oregonstate.education/computationalbiology/)
38) [Computational Genomics with R](http://compgenomr.github.io/book/)
39) [The Biologist's Guide to Computing](https://book.biologistsguide2computing.com/en/stable/)
40) [Bioinformatics Data Skills](https://www.oreilly.com/library/view/bioinformatics-data-skills/9781449367480/)
41) [The Supplementary Material Repository for Bioinformatics Data Skills](https://github.com/vsbuffalo/bds-files/)
42) [From cell line to command line](https://divingintogeneticsandgenomics.ck.page/)
43) [Introduction to Unix, Orchestra and RNA-Seq](https://wiki.harvard.edu/confluence/display/hbctraining/Introduction+to+Unix%2C+Orchestra+and+RNA-Seq)
44) [Linux command line exercises for NGS data processing](https://userweb.eng.gla.ac.uk/umer.ijaz/bioinformatics/linux.html)
45) [Introduction to Unix](https://www.melbournebioinformatics.org.au/tutorials/tutorials/unix/unix/)
46) [Learn about Bioinformatics and Computational Tools for Biology](http://barc.wi.mit.edu/education/)
47) [Introduction to R for Biologists](https://melbournebioinformatics.github.io/r-intro-biologists/intro_r_biologists.html#R_for_Biologists_course)
48) [Explore the world of Bioinformatics with Machine Learning](https://www.kdnuggets.com/2019/09/explore-world-bioinformatics-machine-learning.html)
49) [Deep learning on computational biology and bioinformatics tutorial](https://theaisummer.com/deep-learning-biology-alphafold/)
50) [HarvardX Biomedical Data Science Open Online Training](http://rafalab.dfci.harvard.edu/pages/harvardx.html)
51) [Folding@Home](https://foldingathome.org/)
52) [Python for biologists](https://pythonforbiologists.com/)
53) [Machine learning for biology part one](https://pythonforbiologists.com/machine-learning-for-biology-part-one.html)
54) [Machine learning for biology part two](https://pythonforbiologists.com/machine-learning-for-biology-part-two.html)
55) [Machine learning for biology part three](https://pythonforbiologists.com/machine-learning-for-biology-part-three.html)
56) [Machine learning for biology part four](https://pythonforbiologists.com/machine-learning-for-biology-part-four.html)
57) [Biopython](https://biopython.org/)
58) [The Biostar Handbook. A bioinformatics e-book for beginners](https://www.biostars.org/p/225812/)
59) [Graphs and Networks for Biology using R](http://web.stanford.edu/class/bios221/NetworkSlides.html)
60) [Bioinformatics in the Tidyverse](https://chapmandu2.github.io/post/2017/02/21/bioinformatics-in-the-tidyverse/)
61) [Cleva Lab Biology](https://www.clevalab.com/blog)
62) [Modeling Life](https://modelinginbiology.github.io/)

## Bioinformatics Tutorials

1)  [Childhood Cancer Data Lab Workshop Materials](https://www.ccdatalab.org/workshop-materials)
2)  [Childhood Cancer Data Lab Research Resources](https://www.ccdatalab.org/research-resources)
3)  [Crash Courses in Bioinformatics](http://crashcourses.biodata.pt/)
4)  [Analysing the HIV pandemic, Part 1: HIV in sub-Sahara Africa](https://rviews.rstudio.com/2019/04/30/analysing-hiv-pandemic-part-1/)
5)  [Analysing the HIV pandemic, Part 2: Drug resistance testing](https://rviews.rstudio.com/2019/05/07/pipeline-for-analysing-hiv-part-2/)
6)  [Analysing the HIV pandemic, Part 3: Genetic diversity](https://rviews.rstudio.com/2019/05/16/pipeline-for-analysing-hiv-part-3/)
7)  [Analysing the HIV pandemic, Part 4: Classification of lab samples](https://rviews.rstudio.com/2019/05/23/pipeline-for-analysing-hiv-part-4/)
8)  [Oncology Bioinformatics project tutorial](https://darkomedin-datascience.medium.com/oncology-bioinformatics-project-tutorial-differential-gene-expression-and-biomarker-discovery-d3ac07db5652)
9)  [Centre of Bioinformatics Research and Technology (CBIRT)](https://cbirt.net/)
10) [Galaxy Training](https://training.galaxyproject.org/training-material/)
11) [GENOMES ARISING](https://www.science.org/content/article/africans-begin-take-reins-research-their-own-genomes)
12) [The next chapter for African genomics](https://www.nature.com/articles/d41586-020-00454-1)
13) [EVOLUTION AND GENOMICS](https://evomics.org/learning/)
14) [gget](https://pachterlab.github.io/gget/)
15) [Data Carpentry for Biologists](https://datacarpentry.org/semester-biology/)
16) [Illustrating Python via Examples from Bioinformatics](http://hplgit.github.io/bioinf-py/doc/pub/html/index.html)
17) [Illustrating Python via Bioinformatics Examples](http://hplgit.github.io/bioinf-py/doc/pub/bioinf-py.html)
18) [Biostatistics for Biomedical Research](https://hbiostat.org/bbr/)
19) [An Introduction to R through the tidyverse + Bioinformatics](https://pmacdasci.github.io/r-intro-tidyverse/)
20) [Learn Bioinformatics in 100 hours](https://www.biostarhandbook.com/edu/course/1/)
21) [Fundamentals of computational biology](https://camilogarciabotero.github.io/biocomp-book/)
22) [Bioinformatics training materials](https://github.com/sib-swiss/training-collection)
23) [Bioinformatics Workbook](https://bioinformaticsworkbook.org/)
24) [Bioinformatics Introduction](https://github.com/SexChrLab/BioinformaticsIntroduction)
25) [Diving into Genetics and Genomics](http://crazyhottommy.blogspot.com/)
26) [Bioinformatics Tutorials](https://www.hadriengourle.com/tutorials/)
27) [MicroArray Project](https://rpubs.com/bilalhamdanieh/bioconductor)
28) [Bioinformatics Midterm Project](https://rpubs.com/nupurjoshi829/546190)
29) [Introduction to bioinformatics](https://rpubs.com/sonnyc247/PCL368-S1-2022)
30) [Genomics Boot Camp](https://genomicsbootcamp.github.io/book/)
31) [Bioinformatics Data Skills (2015)](https://apprize.best/data/bioinformatics/)
32) [The Bioconductor 2018 Workshop Compilation](https://bioconductor.github.io/BiocWorkshops/)
33) [Bioconductor Workshop 1 Jupyter Notebooks](https://compbiocore.github.io/bioconductor-workshop-1/notebook/)
34) [Genomic Data Processing](https://gdc.cancer.gov/about-data/gdc-data-processing/genomic-data-processing)
35) [Machine Learning in Genomics Workshop](https://www.genome.gov/event-calendar/Machine-Learning-in-Genomics-Tools-Resources-Clinical-Applications-and-Ethics)
36) [PiGx: Pipelines in Genomics](http://bioinformatics.mdc-berlin.de/pigx/)
37) [USC Libraries Bioinformatics](https://libguides.usc.edu/c.php?g=1024275&p=7420352)
38) [NCI Bioinformatics Training and Education Program](https://btep.ccr.cancer.gov/classes/rbioconductor-basics-workshop-2-day-3/)
39) [Harvard Chan Bioinformatics Core](https://bioinformatics.sph.harvard.edu/training)
40) [First Steps in Biopython](https://krother.gitbooks.io/biopython-tutorial/content/first_steps.html)
41) [What is BioPython](https://notebook.community/gditzler/bio-course-materials/notebooks/BioPython-Tutorial)
42) [Getting Started with Biopython](https://www.kaggle.com/code/mylesoneill/getting-started-with-biopython/notebook)
43) [Biopython Tutorial](https://www.tutorialspoint.com/biopython/index.htm)
44) [Practical Computing for Biologists](https://people.duke.edu/~ccc14/pcfb/biopython/BiopythonBasics.html)
45) [Biopython Tutorial and Cookbook](http://biopython.org/DIST/docs/tutorial/Tutorial.html)
46) [A Primer on Deep Learning in Genomics](https://colab.research.google.com/drive/17E4h5aAOioh5DiTo7MZg4hpL6Z_0FyWr#scrollTo=IA9FJeQkr1Ze)
47) [A Primer for Computational Biology](https://open.oregonstate.education/computationalbiology/)
48) [My opinionated selection of books/urls for bioinformatics/data science curriculum](https://divingintogeneticsandgenomics.rbind.io/post/my-opinionated-selection-of-books-for-bioinformatics-data-science-curriculum/)
49) [PCA in action](https://divingintogeneticsandgenomics.rbind.io/post/pca-in-action/)
50) [ROSALIND](https://rosalind.info/problems/locations/)
51) [Intro to R and RStudio for Genomics](https://datacarpentry.org/genomics-r-intro/)
52) [Free online training in bioinformatics and biostatistics](https://pickingupthetabb.wordpress.com/building-a-bioinformaticist/free-online-training-in-bioinformatics-and-biostatistics/)
53) [Statistical Modeling of High Dimensional Counts](https://mikelove.github.io/counts-model/)
54) [Free and Open Source Tools for Bioinformatics and Molecular Biology](https://www.opensourceforu.com/2018/03/free-open-source-tools-bioinformatics-molecular-biology/)
55) [R for Biology Data Science](https://jmhulbert.github.io/r/bio/s1/)
56) [Griffith Lab Tutorials and Courses](https://griffithlab.org/teaching/)
