---
title: "Biotechnology Startups and Open-Source Bio"
toc: true
---

## Resources for Biotechnology Startups

1)  [biotickr](https://biotickr.com/)
2)  [Investor Village Biotech and Med](https://www.investorvillage.com/groups.asp?mb=20628&mn=21&pt=msg&mid=22867286)
3)  [Biotech2k Background Info](https://www.biotech2k.com/learning/science.html)
4)  [Alcimed Biotech Business Exploration](https://www.alcimed.com/en/terres-exploration/biotech/)
5)  [Benchmarks for growing health tech businesses](https://www.bvp.com/atlas/benchmarks-for-growing-health-tech-businesses)
6)  [The best ways to follow biopharma news and learn about the industry (in my opinion)](https://atelfo.github.io/2022/03/19/the-best-way-to-follow-biopharma-news.html)
7)  [Timmerman Report: Your edge in Biotech](https://timmermanreport.com/)
8)  [How to start a biotech company](https://www.alacrita.com/blog/how-to-start-a-biotech-company)
9)  [How to Build a Biotech](https://www.celinehh.com/how-to-build-a-biotech)
10) [Scaling Biotech](https://scalingbiotech.com/)
11) [Anatomy of a Biotech Business Development Deal](https://a16z.com/2022/01/25/anatomy-of-a-biotech-business-development-deal-2/)
12) [The case for young biotech founders](https://www.baybridgebio.com/blog/young_founders.html)
13) [Data-driven perspectives on the business of biotech](https://www.baybridgebio.com/blog.html)
14) [The Bio Revolution](https://www.mckinsey.com/industries/life-sciences/our-insights/the-bio-revolution-innovations-transforming-economies-societies-and-our-lives)
15) [Synthetic Biology Is About to Disrupt Your Industry](https://www.bcg.com/publications/2022/synthetic-biology-is-about-to-disrupt-your-industry)
16) [Investing in IDRx](https://a16z.com/2022/08/02/investing-in-idrx/)
17) [Why We're Investing in EQRx](https://a16z.com/2020/01/12/why-were-investing-in-eqrx/)
18) [Term Sheet Recommendations for Launching University Life Science Startups](https://techventures.columbia.edu/term-sheet-recommendations-for-launching-university-startups)
19) [How Do You Become a Bioentrepreneur?](https://kcorazo.medium.com/how-do-you-become-a-bioentrepreneur-2f14a91c5f35)
20) [How to Spin Your Scientific Research Out Of a University and Into a Startup](https://www.ycombinator.com/library/8f-how-to-spin-your-scientific-research-out-of-a-university-and-into-a-startup)
21) [Early-Stage Biotech Value Creation: The Roles of Equity and Partnerships](https://leadershipandbiotechnology.blogspot.com/2018/08/early-stage-biotech-value-creation_15.html)
22) [How Biotech Startup Funding Will Change in the Next 10 Years](https://www.ycombinator.com/blog/how-biotech-startup-funding-will-change-in-the-next-10-years/)
23) [The Creation Of Biotech Startups: Evolution Not Revolution](https://lifescivc.com/2019/08/the-creation-of-biotech-startups-evolution-not-revolution/)
24) [Biotech New Venture Formation: Reflecting On A Decade's Changing Dynamics](https://lifescivc.com/2015/12/biotech-new-venture-formation-reflecting-on-a-decades-changing-dynamics/)
25) [Biotech researchers venture into the wild to start their own business](https://techcrunch.com/2019/08/09/biotech-researchers-venture-into-the-wild-to-start-their-own-business/)
26) [Platform-Disease Fit: Why You Need It and How to Find It](https://a16z.com/2021/01/08/platform-disease-fit/)
27) [It's Time to Heal: 16 Trends Driving the Future of Bio and Healthcare](https://a16z.com/2021/01/08/its-time-to-heal-16-trends-driving-the-future-of-bio-and-healthcare/)

## Open-Source Science, Medicine, and Technology

1)  [PloS Open Source Toolkit](https://collections.plos.org/channel/open-source-toolkit/)
2)  [Synthetic Biology for engineering plant growth](https://haseloff.plantsci.cam.ac.uk/)
3)  [Open sourcing bioinstruments](https://liorpachter.wordpress.com/2019/01/18/open-sourcing-bioinstruments/)
4)  [Open Source Tools for Computational Biology](https://www.pillar.vc/playlist/article/open-source-tools-for-computational-biology/)
5)  [Andre Maia Chagas Open-Source](https://amchagas.github.io/)
6)  [Open Neuroscience](https://open-neuroscience.com/)
7)  [Open Source BioArt](https://www.hackteria.org/)
8)  [Open Labware](https://badenlab.org/open-labware-net/)
9)  [Open Source Hardware Journal](https://www.hardware-x.com/)
10) [TREND Africa Open Source Training](https://trendinafrica.org/)
11) [Open Source Biomaker](https://www.biomaker.org/)
12) [Hackaday Open Source](https://hackaday.io/)
13) [DIY BIO](https://diybio.org/local/)
14) [Open Source Bioreactor](https://sites.google.com/site/opensourcebioreactor/)
15) [Open Source Bioreactor Project](https://openbioeconomy.org/projects/open-source-bioreactor/)
16) [Farma: a Home Bioreactor for Pharmaceutical Drugs](https://www.instructables.com/Farma-an-at-home-bioreactor-for-pharmaceutical-dru/)
17) [Gaudi Labs Open Culture Technology](http://www.gaudi.ch/GaudiLabs/)
18) [Raspberry Pi: a versatile tool for biological sciences](https://www.raspberrypi.com/news/raspberry-pi-a-versatile-tool-for-biological-sciences/)
19) [Appropedia: Open Source Technology](https://www.appropedia.org/Welcome_to_Appropedia)
20) [Open-source robotic platform for experimental automation](https://chi.bio/)
21) [DFROBOT](https://community.dfrobot.com/)
22) [IFIXIT](https://www.ifixit.com/Device/Medical_Device)
23) [Lab On The Cheap](https://www.labonthecheap.com/)
24) [DIYbio Lab](https://hackaday.io/project/11641-diybio-lab)
25) [Biodesign Sprint](https://www.biodesignsprint.org/)
26) [Open Data Kit](https://opendatakit.org/)
27) [Open mHealth](https://www.openmhealth.org/)
28) [Mobile Sensor Data to Knowledge](https://md2k.org/)
29) [Algae Biomanufacturing](https://provectusalgae.com/)
