---
title: "RStudio and Carpentries Certification"
toc: true
---

## RStudio Certification

1)	[R4DS Book – Prep for Exam](https://sciencificity.github.io/R4DS_study_exams/index.html)
2)	[POSIT/R Training Videos](https://posit.co/resources/videos/) 
3)	[POSIT Primers](https://posit.cloud/learn/primers)
4)	[RStudio Sample Exams](https://education.rstudio.com/blog/2020/08/more-example-exams/)
5)	[Laurie L Baker RStudio Instructor Training](https://github.com/LaurieLBaker/r-studio-instructor-training)
6)	[Marly Comar Gotti Tidyverse Certification](https://marlycormar.github.io/tidyverse_sample_exam/sample_exam_sols/sols.html)
7)	[Yuqi Liao: Getting Certified as an RStudio Instructor](https://www.yuqiliao.com/blog/rstudiocertification/)
8)	[Shel Kariuki: The RStudio Certification Process](https://shelkariuki.netlify.app/blog/certification/)
9)	[Florencia D’Andrea: Two examples of iteration with purrr - Class for the RStudio certification](https://florencia.netlify.app/blog/two-examples-of-iteration-with-purrr.en-us/)
10)	[Silvia Canelon RStudio Certification](https://silviacanelon.com/blog/2020-rstudio-instructor-certification-tidyverse/)
11)	[Silvia Canelon RStudio Certification Training 1](https://spcanelon.github.io/rit-tidyverse-exam/14-strings/index.html#1)
12)	[Silvia Canelon RStudio Certification Training 2](https://spcanelon.github.io/rit-tidyverse-exam/21-iteration/index.html#1)
13)	[Silvia Canelon R4DS Certification Training 1](https://r4ds.github.io/bookclub-R_for_Data_Science/Presentations/Week04/Cohort1/Chapter5Slides.html#1)
14)	[Paloma Rojas Saunero RStudio Certification Training 1](https://palolili23.github.io/texam/teaching_exam.html)
15)	[Paloma Rojas Saunero RStudio Certification Exam Slides](https://palolili23.github.io/texam/slides.html#1)
16)	[Paloma Rojas Saunero RStudio Certification Exam Notes](https://palolili23.github.io/texam/tidyr.html)
17)	[Miscellaneous Teaching Notes 1](https://docs.google.com/document/d/17mDR_Tup5aSA_Qc2HZaFB8TloGDDUnjxnD4bPWdkseA/edit)
18)	[Miscellaneous Teaching Notes 2](https://docs.google.com/document/d/1uEWz_dMtky2Zjrq8CMFL7Zls-55Ig8KrrdVGwSiw3PI/edit) 

## Carpentries Certification

1)	[The Carpentries](https://carpentries.org/)
2)	[Data Carpentry](https://datacarpentry.org/lessons/)
3)	[Software Carpentry](https://software-carpentry.org/lessons/)
4)	[Library Carpentry](https://librarycarpentry.org/lessons/) 

