---
title: "Statistics"
toc: true
---

## Basics

1)	[Introduction to Modern Statistics](https://openintro-ims.netlify.app/index.html)
2)	[Statistical Thinking](https://www.fharrell.com/)
3)	[Statistics 110: Probability](https://projects.iq.harvard.edu/stat110)
4)	[Causal Inference: What If (Hernan MA)](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)
5)	[Bayes Rules!](https://bayesf22-notebook.classes.andrewheiss.com/bayes-rules/)
6)	[Statistical Computing](https://www.stephaniehicks.com/jhustatcomputing2022/schedule)
7)	[Welcome to A/B Testing at Scale Tutorial](https://exp-platform.com/2017abtestingtutorial/)
8)	[Causal Inference: The Mixtape](https://mixtape.scunning.com/)
9)	[BIOLOGY FOR LIFE](https://www.biologyforlife.com/statistics.html)
10)	[Statistical Problems to Document and to Avoid](https://discourse.datamethods.org/t/author-checklist/3407)
11)	[Datamethods](https://discourse.datamethods.org/)
12)	[Seeing Theory](https://seeing-theory.brown.edu/index.html)
13)	[Causation and Correlation](https://blog.ephorie.de/causation-doesnt-imply-correlation-either)
14)	[Common statistical tests are linear models (or: how to teach stats)](https://lindeloev.github.io/tests-as-linear/)
15)	[An Introduction to Hierarchical Modeling](http://mfviz.com/hierarchical-models/)
16)	[Tidy Statistics in R](https://themockup.blog/posts/2018-12-10-a-gentle-guide-to-tidy-statistics-in-r/)
17)	[Program Evaluation for Public Service and Research Design](https://evalsp20.classes.andrewheiss.com/)
18)	[Statistics and R](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html)
19)	[R and statsExpressions](https://indrajeetpatil.github.io/statsExpressions/)
20)	[A Gentle Guide to Tidy Statistics in R](https://themockup.blog/posts/2018-12-10-a-gentle-guide-to-tidy-statistics-in-r/)
21)	[Modern Statistics with R](https://modernstatisticswithr.com/)
22)	[Power Analysis | Introduction in R](https://newpblog.netlify.app/2021-11-19-bit-by-bit-power-analysis/)
23)	[Regression Modelling in R](https://chrismainey.github.io/Regression_Modelling_NHSR/Regression_modelling#1)
24)	[The Grammar of Experimental Design](https://emitanaka.org/slides-useR2021/#1)
25)	[Bayes Rules! An Introduction to Applied Bayesian Modeling](https://www.bayesrulesbook.com/)
26)	[Statistical rethinking with brms, ggplot2, and the tidyverse](https://bookdown.org/content/4857/)
27)	[Statistics 431: Advanced Statistical Computing with R](https://cal-poly-advanced-r.github.io/STAT-431/)
28)	[Design and Analysis of Experiments and Observational Studies using R](http://designexptr.org/index.html)
29)	[Introduction to Probability for Data Science](https://probability4datascience.com/)
30)	[metrica: Prediction performance metrics](https://adriancorrendo.github.io/metrica/index.html)
31)	[STA 363: Statistical Learning](https://sta-363-s20.lucymcgowan.com/)
32)	[STA 312: Linear Models](https://sta-312-f20.netlify.app/)
33)	[STA 212: Statistical Models](https://sta-212-f19.lucymcgowan.com/)
34)	[Bayes 1](https://betterexplained.com/articles/an-intuitive-and-short-explanation-of-bayes-theorem/)
35)	[Bayes 2](https://betterexplained.com/articles/understanding-bayes-theorem-with-ratios/)
36)	[Intro to Bayesian Business Analytics](https://www.causact.com/index.html#welcome)
37)	[CausalImpact](https://google.github.io/CausalImpact/CausalImpact.html)
38)	[GUide to STatistical Analysis in Microbial Ecology (GUSTA ME) ](https://sites.google.com/site/mb3gustame/)

## Biostatistics

1)	[Biostatistics for Biomedical Research](https://hbiostat.org/bbr/) 
2)	[Tutorials in Biostatistics Papers](https://onlinelibrary.wiley.com/page/journal/10970258/homepage/tutorials.htm)
3)	[Biostatistics Series Papers](https://scholar.google.com/scholar?start=0&q=avijit+hazra+biostatistics&hl=en&as_sdt=0,5) 
4)	[WCM Biostatistics Computing Club](https://wcm-computing-club.github.io/index.html)
5)	[Katherine (Kat) Hoffman Biostats](https://www.khstats.com/)


